### ISSUE TITLE
Images in the timeline stop loading with error "500. That's an error."

### ISSUE THREAD

**Issue by mendel5** [cloudrac3r/bibliogram#94] opened 2020-06-27 17:54 UTC
Some days ago I came across the profile https://bibliogram.art/u/maripiermorin . After scrolling down some pages, the images in the timeline stopped loading and an error message was displayed saying "500. That's an error.".

The detailed error message can be seen in the screenshot:
![bibliogram-maripiermorin](https://user-images.githubusercontent.com/60322520/85928732-78946480-b8af-11ea-970a-17628f17da41.png)

At the time of writing this I am not able to reproduce this issue.

**Comment by FireMasterK** [comment] 2020-06-29 06:13
https://bibliogram.art/u/maripiermorin?page=7
Nginx gives a 504 gateway timeout

**Comment by cloudrac3r** [comment] 2020-07-16 11:42
Might be fixed by 8f0890f0ada8b8e73c76510754e3e0ebb8930add. I can't reproduce it.

**Closed by cloudrac3r** 2020-07-16 11:42 UTC
Labels: bug, cannot reproduce
